"""empty message

Revision ID: a2375eb08240
Revises: 73f47022576d
Create Date: 2021-05-26 13:39:37.349173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2375eb08240'
down_revision = '73f47022576d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notion_integration_key', sa.String(), nullable=True))
    op.add_column('users', sa.Column('database_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('label', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'label')
    op.drop_column('users', 'database_id')
    op.drop_column('users', 'notion_integration_key')
    # ### end Alembic commands ###
